# Declaring the user list
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: loki-auth
spec:
  basicAuth:
    secret: loki-basic-auth

---
apiVersion: v1
kind: Secret
metadata:
  name: loki-basic-auth
  namespace: loki
type: kubernetes.io/basic-auth
data:
  username: YWRtaW4=
  password: YWRtaW5AZ3JvdXAwMQ==