apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 10m
  releaseName: prometheus
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '65.0.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-values
      valuesKey: values.yml

