# Declaring the user list
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: prometheus-auth
spec:
  basicAuth:
    secret: prometheus-basic-auth

---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth
  namespace: monitoring
type: kubernetes.io/basic-auth
data:
  username: YWRtaW4=
  password: YWRtaW5AZ3JvdXAwMQ==