apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IudGgxZW5sbTAyLmxpdmUiOnsidXNlcm5hbWUiOiJyb2JvdCRncm91cDAzIiwicGFzc3dvcmQiOiJqVUllYTJCZ2RDNnZNb2JDVFBlOGJsOHE1eDBKWXlrOCIsImF1dGgiOiJjbTlpYjNRa1ozSnZkWEF3TXpwcVZVbGxZVEpDWjJSRE5uWk5iMkpEVkZCbE9HSnNPSEUxZURCS1dYbHJPQT09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: harbor-secret
type: kubernetes.io/dockerconfigjson