apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-mysql-configmap
data:
  dbName: auth_service
  BASE_URL_FE: https://application.th1enlm02.live

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-mysql-initdb
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS auth_service;
    USE auth_service;
    CREATE TABLE IF NOT EXISTS auth (
      id INT AUTO_INCREMENT PRIMARY KEY,
      email VARCHAR(255) NOT NULL,
      password VARCHAR(255) NOT NULL
    );
