apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: auth-service-repo
spec:
  image: harbor.th1enlm02.live/production/class-management-auth-service
  interval: 20s
  provider: generic
  secretRef:
    name: harbor-secret

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: auth-service-policy
spec:
  imageRepositoryRef:
    name: auth-service-repo
  filterTags:
    pattern: '^[a-fA-F0-9]+-(?P<ts>.*)$'
    extract: '$ts'
  policy:
    numerical:
      order: asc

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: auth-service-img
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: Flux
      messageTemplate: 'Release Production'
    push:
      branch: main
  update:
    path: ./manifests/base/class-management-auth-service
    strategy: Setters
