apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: class-management-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class-management-fe
  template:
    metadata:
      labels:
        app: class-management-fe
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: class-management-fe-container
          image: harbor.th1enlm02.live/production/class-management-fe:ff440b3-1734259497 # {"$imagepolicy": "production:frontend-policy"}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BASE_URL_AUTH
              valueFrom:
                configMapKeyRef:
                  name: base-url-configmap
                  key: REACT_APP_BASE_URL_AUTH
            - name: REACT_APP_BASE_URL_STUDENT
              valueFrom:
                configMapKeyRef:
                  name: base-url-configmap
                  key: REACT_APP_BASE_URL_STUDENT
            - name: REACT_APP_BASE_URL_LECTURER
              valueFrom:
                configMapKeyRef:
                  name: base-url-configmap
                  key: REACT_APP_BASE_URL_LECTURER
            - name: REACT_APP_BASE_URL_CLASS
              valueFrom:
                configMapKeyRef:
                  name: base-url-configmap
                  key: REACT_APP_BASE_URL_CLASS
