resources:
  - ../../base
  - namespace.yml
namespace: staging
patches:
  # - path: ./class-management-fe/ingress.yml
  # # - path: ./class-management-fe/configMap.yml
  # - path: ./class-management-auth-service/ingress.yml
  # # - path: ./class-management-auth-service/configMap.yml
  # - path: ./class-management-student-service/ingress.yml
  # - path: ./class-management-lecturer-service/ingress.yml
  # - path: ./class-management-class-service/ingress.yml
  - path: ./ingress-patches.yml
  - path: ./configMap-patches.yml
  - path: ./vault-patches.yml