apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "readonly"
        vault.hashicorp.com/template-static-secret-render-interval: "10s"
        vault.hashicorp.com/agent-inject-secret-auth: "nt548p11/data/staging/auth/service"
        vault.hashicorp.com/agent-inject-template-auth: |
          {{- with secret "nt548p11/data/staging/auth/service" -}}
            {{- range $key, $value := .Data.data -}}
              export {{ $key }}="{{ $value }}" \n
            {{- end }}
          {{- end }}
    spec:
      serviceAccountName: vault-sa
      containers:
        - name: class-management-auth-service-container
          command: ["/bin/sh", "-c"]
          args: ["source /vault/secrets/auth && node server.js"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mysql-deployment
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "readonly"
        vault.hashicorp.com/template-static-secret-render-interval: "10s"
        vault.hashicorp.com/agent-inject-secret-auth: "nt548p11/data/staging/auth/database"
        vault.hashicorp.com/agent-inject-template-auth: |
          {{- with secret "nt548p11/data/staging/auth/database" -}}
            {{- range $key, $value := .Data.data -}}
              export {{ $key }}="{{ $value }}" \n
            {{- end }}
          {{- end }}
    spec:
      serviceAccountName: vault-sa
      containers:
        - name: auth-service-mysql-container
          command: ["/bin/sh", "-c"]
          args: ["source /vault/secrets/auth && docker-entrypoint.sh mysqld"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-deployment
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "readonly"
        vault.hashicorp.com/template-static-secret-render-interval: "10s"
        vault.hashicorp.com/agent-inject-secret-class: "nt548p11/data/staging/class/service"
        vault.hashicorp.com/agent-inject-template-class: |
          {{- with secret "nt548p11/data/staging/class/service" -}}
            {{- range $key, $value := .Data.data -}}
              export {{ $key }}="{{ $value }}" \n
            {{- end }}
          {{- end }}
    spec:
      containers:
        - name: class-management-class-service-container
          command: ["/bin/sh", "-c"]
          args: ["source /vault/secrets/class && apache2-foreground"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-postgresql-deployment
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "readonly"
        vault.hashicorp.com/template-static-secret-render-interval: "10s"
        vault.hashicorp.com/agent-inject-secret-class: "nt548p11/data/staging/class/database"
        vault.hashicorp.com/agent-inject-template-class: |
          {{- with secret "nt548p11/data/staging/class/database" -}}
            {{- range $key, $value := .Data.data -}}
              export {{ $key }}="{{ $value }}" \n
            {{- end }}
          {{- end }}
    spec:
      containers:
        - name: class-service-postgresql-container
          command: ["/bin/sh", "-c"]
          args: ["source /vault/secrets/class && docker-entrypoint.sh postgres"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecturer-deployment
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "readonly"
        vault.hashicorp.com/template-static-secret-render-interval: "10s"
        vault.hashicorp.com/agent-inject-secret-lecturer: "nt548p11/data/staging/lecturer/service"
        vault.hashicorp.com/agent-inject-template-lecturer: |
          {{- with secret "nt548p11/data/staging/lecturer/service" -}}
            {{- range $key, $value := .Data.data -}}
              export {{ $key }}="{{ $value }}" \n
            {{- end }}
          {{- end }}
      containers:
        - name: class-management-lecturer-service-container
          command: ["/bin/sh", "-c"]
          args: ["source /vault/secrets/lecturer && python app.py"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecturer-mongodb-deployment
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "readonly"
        vault.hashicorp.com/template-static-secret-render-interval: "10s"
        vault.hashicorp.com/agent-inject-secret-lecturer: "nt548p11/data/staging/lecturer/database"
        vault.hashicorp.com/agent-inject-template-lecturer: |
          {{- with secret "nt548p11/data/staging/lecturer/database" -}}
            {{- range $key, $value := .Data.data -}}
              export {{ $key }}="{{ $value }}" \n
            {{- end }}
          {{- end }}
    spec:
      containers:
        - name: lecturer-service-mongodb-container
          command: ["/bin/sh", "-c"]
          args: ["source /vault/secrets/lecturer && docker-entrypoint.sh mongod"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deployment
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "readonly"
        vault.hashicorp.com/template-static-secret-render-interval: "10s"
        vault.hashicorp.com/agent-inject-secret-student: "nt548p11/data/staging/student/service"
        vault.hashicorp.com/agent-inject-template-student: |
          {{- with secret "nt548p11/data/staging/student/service" -}}
            {{- range $key, $value := .Data.data -}}
              export {{ $key }}="{{ $value }}" \n
            {{- end }}
          {{- end }}
    spec:
      containers:
        - name: class-management-student-service-container
          command: ["/bin/sh", "-c"]
          args: ["source /vault/secrets/student && java -jar app.jar"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-mysql-deployment
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "readonly"
        vault.hashicorp.com/template-static-secret-render-interval: "10s"
        vault.hashicorp.com/agent-inject-secret-student: "nt548p11/data/staging/student/database"
        vault.hashicorp.com/agent-inject-template-student: |
          {{- with secret "nt548p11/data/staging/student/database" -}}
            {{- range $key, $value := .Data.data -}}
              export {{ $key }}="{{ $value }}" \n
            {{- end }}
          {{- end }}
    spec:
      containers:
        - name: student-service-mysql-container
          command: ["/bin/sh", "-c"]
          args: ["source /vault/secrets/student && docker-entrypoint.sh mysqld"]