apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  selector:
    app: class-management-student-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: student-service-mysql
spec:
  selector:
    app: student-service-mysql
  type: ClusterIP
  ports:
    - port: 3307
      targetPort: 3306
