apiVersion: v1
kind: PersistentVolume
metadata:
  name: stag-auth-mysql-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2