apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 10m
  releaseName: loki
  chart:
    spec:
      chart: loki
      version: '6.16.0'
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
  valuesFrom:
    - kind: ConfigMap
      name: loki-values
      valuesKey: values.yml
