chunksCache:
  allocatedMemory: 500

loki:
  auth_enabled: false
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  storage:
    # filesystem: null
    type: s3
    bucketNames:
      chunks: "devops"
      ruler: "devops"
      admin: "admin"
    s3:
      s3: "s3://ogXBMfE3Xi5Oypz9G2Bo:ogXBMfE3Xi5Oypz9G2Bo@10.0.30.10:9000/devops"
      insecure: true
      s3ForcePathStyle: true

deploymentMode: SingleBinary


singleBinary:
  replicas: 1
  persistence:
    enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

