apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: loki
spec:
  interval: 10m
  releaseName: promtail
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
  valuesFrom:
    - kind: ConfigMap
      name: promtail-values
      valuesKey: values.yml

