apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: class-service-repo
spec:
  image: harbor.th1enlm02.live/staging/class-management-class-service

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: class-service-img
spec:
  update:
    path: ./manifests/overlays/staging/class-management-class-service
    strategy: Setters
